# Generated by Django 4.2.7 on 2025-10-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coaching", "0002_module_specialtimesession_moduleprogress_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="completion_rules",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Criteria to mark module as passed (e.g., {'sessions_21d': 6, 'liked_last6': 4})",
                verbose_name="completion rules",
            ),
        ),
        migrations.AlterField(
            model_name="moduleprogress",
            name="state",
            field=models.CharField(
                choices=[
                    ("locked", "Locked - prerequisites not met"),
                    ("unlocked", "Unlocked - available to start"),
                    ("passed", "Passed - module completed successfully"),
                ],
                default="locked",
                help_text="Current state of this module for this child",
                max_length=10,
                verbose_name="state",
            ),
        ),
    ]
