# Generated by Django 4.2.7 on 2025-10-31 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0005_angercrisislog'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeOutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of this log entry', verbose_name='date')),
                ('needed_timeout', models.BooleanField(help_text='Did the parent need to use time-out today?', verbose_name='needed timeout')),
                ('was_successful', models.BooleanField(blank=True, help_text='Did the time-out work? (only if needed)', null=True, verbose_name='was successful')),
                ('failure_reason', models.CharField(blank=True, choices=[('negotiation', 'Child kept negotiating'), ('time_not_respected', 'Time was not respected')], help_text="Why didn't it work? (only if unsuccessful)", max_length=20, null=True, verbose_name='failure reason')),
                ('notes', models.TextField(blank=True, default='', help_text='Optional notes about this time-out', verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeout_logs', to='coaching.child', verbose_name='child')),
            ],
            options={
                'verbose_name': 'time-out log',
                'verbose_name_plural': 'time-out logs',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['child', 'date'], name='coaching_ti_child_i_0483c8_idx'), models.Index(fields=['child', 'was_successful'], name='coaching_ti_child_i_3f9f85_idx')],
                'unique_together': {('child', 'date')},
            },
        ),
    ]
