# Generated by Django 4.2.7 on 2025-10-31 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("coaching", "0006_timeoutlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="Privilege",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "points_cost",
                    models.IntegerField(
                        help_text="Points required to redeem this privilege (3, 5, or 10)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="privileges",
                        to="coaching.child",
                    ),
                ),
            ],
            options={
                "ordering": ["points_cost", "title"],
            },
        ),
        migrations.CreateModel(
            name="DailyTaskCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "completed_task_ids",
                    models.JSONField(
                        default=list,
                        help_text="Array of task IDs completed on this day",
                    ),
                ),
                ("total_points_earned", models.IntegerField(default=0)),
                (
                    "completion_rate",
                    models.FloatField(
                        default=0.0, help_text="Percentage of tasks completed (0-100)"
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_completions",
                        to="coaching.child",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "points_reward",
                    models.IntegerField(
                        help_text="Points earned when task is completed (1, 3, or 5)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="coaching.child",
                    ),
                ),
            ],
            options={
                "ordering": ["points_reward", "title"],
                "indexes": [
                    models.Index(
                        fields=["child", "is_active"],
                        name="coaching_ta_child_i_77e1c9_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PrivilegeRedemption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "privilege_title",
                    models.CharField(
                        help_text="Stored in case privilege is deleted", max_length=200
                    ),
                ),
                ("points_spent", models.IntegerField()),
                ("redeemed_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="privilege_redemptions",
                        to="coaching.child",
                    ),
                ),
                (
                    "privilege",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="redemptions",
                        to="coaching.privilege",
                    ),
                ),
            ],
            options={
                "ordering": ["-redeemed_at"],
                "indexes": [
                    models.Index(
                        fields=["child", "-redeemed_at"],
                        name="coaching_pr_child_i_212855_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="privilege",
            index=models.Index(
                fields=["child", "is_active"], name="coaching_pr_child_i_50b04f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailytaskcompletion",
            index=models.Index(
                fields=["child", "date"], name="coaching_da_child_i_08d2ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailytaskcompletion",
            index=models.Index(
                fields=["child", "-date"], name="coaching_da_child_i_87acb6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailytaskcompletion",
            unique_together={("child", "date")},
        ),
    ]
