# Generated by Django 4.2.7 on 2025-10-31 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("coaching", "0007_privilege_dailytaskcompletion_task_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Routine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "routine_type",
                    models.CharField(
                        choices=[
                            ("morning", "Routine du matin"),
                            ("evening", "Routine du soir"),
                            ("sunday", "Routine du dimanche soir"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "steps",
                    models.JSONField(
                        default=list, help_text="Array of step descriptions (strings)"
                    ),
                ),
                (
                    "target_time",
                    models.TimeField(help_text="Expected completion time (HH:MM)"),
                ),
                (
                    "is_custom",
                    models.BooleanField(
                        default=False,
                        help_text="True if created by parent, False if from template",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routines",
                        to="coaching.child",
                    ),
                ),
            ],
            options={
                "ordering": ["routine_type"],
            },
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Emploi du temps", max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="coaching.child",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_active", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TimeManagementChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approach",
                    models.CharField(
                        choices=[
                            ("routines", "Routines"),
                            ("schedule", "Emploi du temps"),
                            ("both", "Les deux"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "child",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_management_choice",
                        to="coaching.child",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScheduleBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Lundi"),
                            (1, "Mardi"),
                            (2, "Mercredi"),
                            (3, "Jeudi"),
                            (4, "Vendredi"),
                            (5, "Samedi"),
                            (6, "Dimanche"),
                        ],
                        help_text="0=Monday",
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("school", "École"),
                            ("travel", "Trajet"),
                            ("home_activity", "Activité à domicile"),
                            ("leisure", "Loisir"),
                            ("free_time", "Temps libre"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Subject name for school blocks",
                        max_length=100,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#4F46E5",
                        help_text="Hex color code for UI",
                        max_length=7,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="coaching.schedule",
                    ),
                ),
            ],
            options={
                "ordering": ["day_of_week", "start_time"],
                "indexes": [
                    models.Index(
                        fields=["schedule", "day_of_week", "start_time"],
                        name="coaching_sc_schedul_e63e6c_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RoutineCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "routine_type",
                    models.CharField(
                        help_text="Stored for history even if routine deleted",
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "was_on_time",
                    models.BooleanField(
                        help_text="True if completed before target time"
                    ),
                ),
                ("completion_time", models.TimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routine_completions",
                        to="coaching.child",
                    ),
                ),
                (
                    "routine",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completions",
                        to="coaching.routine",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["child", "-date"], name="coaching_ro_child_i_4881a3_idx"
                    ),
                    models.Index(
                        fields=["child", "was_on_time", "-date"],
                        name="coaching_ro_child_i_4972b3_idx",
                    ),
                ],
                "unique_together": {("child", "routine_type", "date")},
            },
        ),
        migrations.AddIndex(
            model_name="routine",
            index=models.Index(
                fields=["child", "is_active"], name="coaching_ro_child_i_09cd15_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="routine",
            index=models.Index(
                fields=["child", "routine_type"], name="coaching_ro_child_i_aa67a8_idx"
            ),
        ),
    ]
