# Generated by Django 4.2.7 on 2025-11-01 10:37

from django.db import migrations


def seed_modules(apps, schema_editor):
    """Seed initial coaching modules."""
    Module = apps.get_model('coaching', 'Module')

    modules = [
        {
            'key': 'special_time',
            'title': 'Moment Spécial',
            'order_index': 1,
            'is_active': True,
            'completion_rules': {
                'min_sessions_21d': 6,
                'min_liked_ratio': 0.66,
            },
        },
        {
            'key': 'effective_commands',
            'title': 'Ordres Efficaces',
            'order_index': 2,
            'is_active': True,
            'completion_rules': {
                'min_objectives': 3,
                'min_satisfying_days': 5,
            },
        },
        {
            'key': 'anger_management',
            'title': 'Gestion de la colère',
            'order_index': 3,
            'is_active': True,
            'completion_rules': {
                'min_successful_crises': 1,
            },
        },
        {
            'key': 'timeout',
            'title': 'Time Out',
            'order_index': 4,
            'is_active': True,
            'completion_rules': {
                'min_successful_timeouts': 3,
            },
        },
        {
            'key': 'rewards',
            'title': 'Le système de point',
            'order_index': 5,
            'is_active': True,
            'completion_rules': {
                'min_consecutive_days': 5,
                'min_completion_rate': 50,
            },
        },
        {
            'key': 'time_management',
            'title': 'La gestion du temps',
            'order_index': 6,
            'is_active': True,
            'completion_rules': {
                'on_time_days_out_of_five': 3,
            },
        },
        {
            'key': 'homework',
            'title': 'Les devoirs scolaires',
            'order_index': 7,
            'is_active': True,
            'completion_rules': {},
        },
    ]

    for module_data in modules:
        Module.objects.get_or_create(
            key=module_data['key'],
            defaults=module_data
        )


def reverse_seed_modules(apps, schema_editor):
    """Remove seeded modules (reversible migration)."""
    Module = apps.get_model('coaching', 'Module')
    module_keys = [
        'special_time',
        'effective_commands',
        'anger_management',
        'timeout',
        'rewards',
        'time_management',
        'homework',
    ]
    Module.objects.filter(key__in=module_keys).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0008_time_management_models'),
    ]

    operations = [
        migrations.RunPython(seed_modules, reverse_seed_modules),
    ]
