# Generated by Django 4.2.7 on 2025-10-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verification_token",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="6-digit code for email verification",
                max_length=6,
                null=True,
                verbose_name="email verification token",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="email_verification_token_expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Expiration time for email verification token",
                null=True,
                verbose_name="email verification token expires at",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this user should be treated as active. Users must verify their email before becoming active.",
                verbose_name="active",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["email_verification_token"],
                name="users_user_email_v_9d9809_idx",
            ),
        ),
    ]
