# Generated by Django 4.2.7 on 2025-10-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_email_verification_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password_reset_token",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="6-digit code for password reset",
                max_length=6,
                null=True,
                verbose_name="password reset token",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="password_reset_token_expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Expiration time for password reset token",
                null=True,
                verbose_name="password reset token expires at",
            ),
        ),
    ]
