# Generated by Django 4.2.7 on 2025-10-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_password_reset_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_guest",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Designates whether this is a temporary guest user. Guest users can be converted to full accounts later.",
                verbose_name="guest user",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True,
                db_index=True,
                error_messages={"unique": "A user with that email already exists."},
                max_length=254,
                null=True,
                unique=True,
                verbose_name="email address",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True,
                db_index=True,
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required for full accounts. 3-30 characters.",
                max_length=30,
                null=True,
                unique=True,
                verbose_name="username",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_guest"], name="users_user_is_gues_a3a003_idx"
            ),
        ),
    ]
