# Generated by Django 4.2.7 on 2025-10-17 14:20

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        help_text="R2 object key (path)",
                        max_length=500,
                        unique=True,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("image", "Image"), ("file", "File")],
                        default="file",
                        help_text="Type of media file",
                        max_length=10,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[("public", "Public"), ("private", "Private")],
                        default="public",
                        help_text="Access control level",
                        max_length=10,
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(help_text="MIME type of the file", max_length=100),
                ),
                (
                    "size_bytes",
                    models.PositiveIntegerField(
                        default=0, help_text="File size in bytes"
                    ),
                ),
                (
                    "width",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Image width in pixels (for images only)",
                        null=True,
                    ),
                ),
                (
                    "height",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Image height in pixels (for images only)",
                        null=True,
                    ),
                ),
                (
                    "sha256",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 hash of the file content",
                        max_length=64,
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Alternative text for accessibility",
                        max_length=255,
                    ),
                ),
                (
                    "meta",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional metadata"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the record was created"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the file was successfully uploaded to R2",
                        null=True,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who uploaded the file",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="media_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Media File",
                "verbose_name_plural": "Media Files",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["owner", "-created_at"],
                        name="media_media_owner_i_aca7d7_idx",
                    ),
                    models.Index(
                        fields=["kind", "visibility"],
                        name="media_media_kind_4bf2d1_idx",
                    ),
                ],
            },
        ),
    ]
